const DataTypes = require('sequelize');

export const CarsTbl = {
    id: {type:DataTypes.INTEGER,primaryKey:true,allowNull:false,autoIncrement:true},
    company_id: {type: DataTypes.INTEGER,allowNull: false},
    vehicle_brand_id: {type: DataTypes.INTEGER,allowNull: false},
    phm_id: {type: DataTypes.INTEGER,allowNull: false},
    insurance_id: {type: DataTypes.INTEGER,allowNull: false},
    car_id: {type: DataTypes.INTEGER,allowNull: false},
    leasing_company_id: {type: DataTypes.INTEGER,allowNull: false},
    responsible_person_id: {type: DataTypes.INTEGER,allowNull: false},
    spz: {type: DataTypes.STRING,allowNull: false},
    speedometer_current_state: {type: DataTypes.INTEGER,allowNull: false},
    vin_code: {type: DataTypes.STRING,allowNull: false},
    year_of_manufacture: {type: DataTypes.INTEGER,allowNull: false},
    technical_license_number: {type: DataTypes.STRING,allowNull: false},
    date_validity_of_road_stamp: {type: DataTypes.DATE,allowNull: false},
    date_appointment_of_service_visits: {type: DataTypes.DATE,allowNull: false},
    date_term_stk: {type: DataTypes.DATE,allowNull: false},
    date_service_according_to_km: {type: DataTypes.DATE,allowNull: false},
    date_service_according_to_month: {type: DataTypes.DATE,allowNull: false},
    date_of_acquisition: {type: DataTypes.DATE,allowNull: false},
    date_of_withdrawal: {type: DataTypes.DATE,allowNull: false},
    engine_capacity: {type: DataTypes.INTEGER,allowNull: false},
    tank_volume: {type: DataTypes.INTEGER,allowNull: false},
    company_center: {type: DataTypes.STRING,allowNull: false},
    average_consumption: {type: DataTypes.INTEGER,allowNull: false},
    speedometer_at_the_time_of_purchase: {type: DataTypes.INTEGER,allowNull: false},
    green_card_number: {type: DataTypes.BIGINT(10),allowNull: false},
    credit_card_number: {type: DataTypes.BIGINT(10),allowNull: false},
    exist: {type: DataTypes.BOOLEAN,allowNull: false},
    createdAt: {type:DataTypes.DATE},
    updatedAt: {type:DataTypes.DATE},
  }